### ISSUE TITLE
An Attribute Plugin link

### ISSUE THREAD

**Issue by Firstmeowwhite** [nosoop/SM-TFCustomAttributeStarterPack#11]
There are no attribute plugin for this pack. So I need a plugin of all custom attributes please.

Sorry for bad English, sir.

**Comment by nosoop** [comment]
I've made a current release with precompiled plugins for you and other interested users; download the `package.zip` available [in the releases page](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/releases).

Make sure the dependencies listed in the README are installed, then install the plugins / gamedata.

**Comment by Firstmeowwhite** [comment]
Thank you!
