### ISSUE TITLE
generate_rage_on_dmg_patch fails verification

### ISSUE THREAD

**Issue by ctf2w-crafting** [nosoop/SM-TFCustomAttributeStarterPack#12]
Not working at this time

(I know you already told me, but this is just a reminder)

**Comment by nosoop** [comment]
Context for future reference:
<pre>
L 02/18/2020 - 16:58:58: [SM] Exception reported: Could not verify patch for CTFGameRules::ApplyOnDamageAliveModifyRules()::DisableHeavyRageDamagePenalty
L 02/18/2020 - 16:58:58: [SM] Blaming: generate_rage_on_dmg_patch.smx
L 02/18/2020 - 16:58:58: [SM] Call stack trace:
L 02/18/2020 - 16:58:58: [SM]   [0] SetFailState
L 02/18/2020 - 16:58:58: [SM]   [1] Line 47, generate_rage_on_dmg_patch.sp::OnPluginStart
</pre>

Ah, yeah; this is one of those likely 'wontfix' cases &mdash; `CTFGameRules::ApplyOnDamageAliveModifyRules()` changes basically every single update, so I can't really be bothered to spend the time disassembling the binary and doing maintenance on this function at that frequency.  Not for free, anyways.

It's possible that there's a more robust raw byte signature within the function, but as of now:
- Source Scramble doesn't have the capability of patching based on raw addresses.
- Discovering / validating such a robust patch needs additional tooling.  I'm like 90% of the way to creating [the base tooling for that](https://gist.github.com/nosoop/82a6195b2140f708a039399b40278cf1), actually.

**Comment by nosoop** [comment]
Have to partially retract my previous comment &mdash; this shouldn't need any changes to Source Scramble.

Going to close this for the time being.  If you'd like to expedite the process of creating a modified patch, feel free to contact me through the other usual channels.

If you'd like to keep the other patches intact and just not use that particular patch, you can comment out lines 23, 44-53, and 66-86.

**Comment by ctf2w-crafting** [comment]
After the change, this is still happening....
```
L 06/01/2020 - 21:24:38: [SM] Exception reported: Could not verify patch for CTFGameRules::ApplyOnDamageAliveModifyRules()::DisableHeavyRageDamagePenalty
L 06/01/2020 - 21:24:38: [SM] Blaming: customweaponstf/custom-attribute-adapter/generate_rage_on_dmg_patch.smx
L 06/01/2020 - 21:24:38: [SM] Call stack trace:
L 06/01/2020 - 21:24:38: [SM]   [0] SetFailState
L 06/01/2020 - 21:24:38: [SM]   [1] Line 47, D:\TF2 Testing Server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\generate_rage_on_dmg_patch.sp::OnPluginStart
L 06/01/2020 - 21:24:38: [SM] Unable to load plugin "customweaponstf/custom-attribute-adapter/generate_rage_on_dmg_patch.smx": Error detected in plugin startup (see error logs)
```

**Comment by nosoop** [comment]
The noted commit does not resolve that issue, just a different one was present that would've been affected.

This issue is still currently considered a 'wontfix' (unless I personally have an incentive to do so in the future), but I've reopened the issue to note that it exists.
