### ISSUE TITLE
Some attributes appear to be ignored by the custom weapons plugin

### ISSUE THREAD

**Issue by Umbrozium** [nosoop/SM-TFCustomAttributeStarterPack#14]
for example, the low gravity demo charge attribute, used with custom-attribute-adapter, is ignored by all attribute plugins.

**Comment by nosoop** [comment]
The Air Lock's configuration is actually bugged; the attribute should be under the `attributes` section instead of `cw3_attributes`.

Make sure that the `custom_weapons_adapter.smx` plugin is installed and running &mdash; you should've seen a warning in the server console that says just that.
