### ISSUE TITLE
attr_rage_meter_mult

### ISSUE THREAD

**Issue by ctf2w-crafting** [nosoop/SM-TFCustomAttributeStarterPack#19]
Both ``banner rage fill multiplier`` and ``rage fill multiplier`` work separately, but not together. For example: This is in tf_custom_attribute config file.....
```
	// Buff Banner
	"129"
	{
		"banner rage fill multiplier"			"0.923077" (NOTE: This increases the cost to 650 from 600)
	}
```
....and I also use this in custom weapons (on a wearable).....
```
		"rage fill multiplier"
		{
			"plugin"	"custom-attribute-adapter" (NOTE: This should be decreasing the cost to 325 from 650)
			"value"		"0.5"
		}
```
Only "banner rage fill multiplier" changes the mult, but not both.

**Comment by ctf2w-crafting** [comment]
NOTE: About "rage fill multiplier"..... I guess it should be 2.0 to cut in half the cost, but these 2 don't stack anyway.

**Comment by nosoop** [comment]
The documentation states that [`rage fill multiplier` is only available on non-wearable items](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/wiki/Custom-Attribute-List#rage-fill-multiplier).
