### ISSUE TITLE
Does ``attr_buff_override`` work on official banners?

### ISSUE THREAD

**Issue by ctf2w-crafting** [nosoop/SM-TFCustomAttributeStarterPack#26]
As a test, I applied ``buff_crit_and_mark_for_death`` to the Battalion's Backup. The icon while under the Battalion's Backup effect doesn't show up (which is good), but the effects are still applied (including the ring around the user). The newer affects do are applied, but the original aren't being removed.

Taken from tf_custom_attributes.txt
```
	// Battalion's Backup
	"226"
	{
		"custom buff type"			"crit-banner"
	}
```

**Comment by ctf2w-crafting** [comment]
Small update. I did switch ``custom buff type`` to ``custom soldier buff type``.... no difference.

**Comment by nosoop** [comment]
They should replace the effect on existing banners with that custom attribute applied (either `custom buff type` or `custom soldier buff type`), yes.

**Comment by ctf2w-crafting** [comment]
I did restart the server while testing, but the problem is still happening (also no errors in the log)

**Comment by nosoop** [comment]
You may have other conflicting plugins (outside of the published starter pack); don't think I can really provide any help there.

**Comment by ctf2w-crafting** [comment]
After removing plugins, I finally found that a plugin was conflicting with ``attr_buff_override``
