### ISSUE TITLE
joke_medigun_mod_drain_health failing to load after recent TF update

### ISSUE THREAD

**Issue by Nolo001-Aha** [nosoop/SM-TFCustomAttributeStarterPack#28]
The plugin simply fails to load with the following stack:
```
L 06/25/2020 - 16:51:15: [SM] Exception reported: Invalid Handle 0
L 06/25/2020 - 16:51:15: [SM] Blaming: customattribs\joke_medigun_mod_drain_health.smx
L 06/25/2020 - 16:51:15: [SM] Call stack trace:
L 06/25/2020 - 16:51:15: [SM]   [0] DHookEnableDetour
L 06/25/2020 - 16:51:15: [SM]   [1] Line 69, joke_medigun_mod_drain_health.sp::OnPluginStart
L 06/25/2020 - 16:51:15: [SM] Unable to load plugin "customattribs\joke_medigun_mod_drain_health.smx": Error detected in plugin startup (see error logs)
```

I am running Windows and I do not run any other plugins that may be detouring the function before this one. 

I am very certain that this is caused by the recent Team Fortress update. I have a local SCRDS with older version of TF, and there it managed to get loaded just fine. Both "production" and "local" servers run the exact same gamedata. 
After updating the local server, however, attempts to load the plugin resulted in the same error stack.

**Server environment (please complete the following information):**
 - Operating System:Windows
 - SourceMod version: 1.10.0.6462

**Comment by nosoop** [comment]
That particular line doesn't correspond to the latest version; can you verify with the source that it should be pointing to this one?

```
DHookEnableDetour(dtCreateRagdoll, false, OnCreateRagdollPre);
```

**Comment by Nolo001-Aha** [comment]
The version that I run has the exact same piece of code on line 69 that you showed.

**Comment by Nolo001-Aha** [comment]
Built a plugin from my source code and attempted to load it to make sure, and yeah it is still line 69.

**Comment by nosoop** [comment]
Thanks &mdash; that suggests that the signature for `CTFPlayer::CreateRagdollEntity()` is also broken.
