### ISSUE TITLE
attr_sapper_reprograms_buildings generating errors

### ISSUE THREAD

**Issue by Nolo001-Aha** [nosoop/SM-TFCustomAttributeStarterPack#29]
The attribute consistently generates errors after recent TF update.

```
L 06/25/2020 - 16:47:25: [SM] Exception reported: Invalid Handle 0 (error 4)
L 06/25/2020 - 16:47:25: [SM] Blaming: customattribs\attr_sapper_reprograms_buildings.smx
L 06/25/2020 - 16:47:25: [SM] Call stack trace:
L 06/25/2020 - 16:47:25: [SM]   [0] SDKCall
L 06/25/2020 - 16:47:25: [SM]   [1] Line 242, attr_sapper_reprograms_buildings.sp::OnPlayerDetonateBuildingPre
L 06/25/2020 - 16:47:25: [SM]   [3] FakeClientCommand
L 06/25/2020 - 16:47:25: [SM]   [4] Line 10991, Unofficial Freak Fortress::OnPlayerDeath
L 06/25/2020 - 16:47:25: [SM]   [6] SDKHooks_TakeDamage
L 06/25/2020 - 16:47:25: [SM]   [7] Line 207, D:\batfo_qrgut13\Documents\SourceMod 1.9 Compiler\addons\sourcemod\scripting\ff2_scp049.sp::OnGameFrame
```
Slight explanation to the stack: Whenever a Freak Fortress boss kills an engineer, their sentry gun gets destroyed via FakeClientCommand.  However, the SDKCall within the plugin does not appear to be functioning anymore and the plugin fails to get the building entity index. 

I am fairly certain that this is also caused by recent Team Fortress update, as no such errors were generated before.

**Server environment (please complete the following information):**
 - Operating System: Windows
 - SourceMod version: 1.10.0.6462

**Comment by nosoop** [comment]
Yeah, it sounds like the `CTFPlayer::GetObjectOfType()` bytesig changed in this instance.  Classic Windows.

Don't have a Windows binary analyzed, expect a fix within the next day or two.

**Comment by nosoop** [comment]
Ah, it wasn't masking an offset within `CTFPlayer`.  Same with #28.

Unfortunately, masking the full offset makes the signature match a bunch of other functions, so instead of extending the signature I'll opt for masking the least significant byte.
