### ISSUE TITLE
damage_increase_on_hit

### ISSUE THREAD

**Issue by ctf2w-crafting** [nosoop/SM-TFCustomAttributeStarterPack#32]
If the user dies with damage stacks, it will not reset. It also doesn't reset if you switch classes. The damage bonus will be applied to whatever the slot was for the new class (aka the secondary damage glitch that happens on my servers). Additional, if the user has stacks, then un-equip the custom weapon outside of spawn then touches a resupply.... the stacks aren't removed.

The only time is correctly removes stacks is when an enemy is killed.

**Comment by ctf2w-crafting** [comment]
https://youtu.be/hRGd2leX0WY

**Comment by nosoop** [comment]
Should be hotfixed in a85e67e1e7748be10ba0264c6868c8fbe0785552, in case you missed it.

One remaining edge case would be that the damage bonus will carry over if the player equips a different weapon in the same slot with the `damage increase mult on hit` attribute and touches resupply, but there's no non-hacky way to fix that without either

- resetting the damage bonus entirely on resupply even if it's the same weapon
- patching up CW{3,4} with the [item persistence fix](https://github.com/nosoop/SM-TFPersistItem) and resetting the damage bonus on a new weapon equip
