### ISSUE TITLE
Sapper Reprograms Building attribute breaks HUD for owner of the sentrygun

### ISSUE THREAD

**Issue by kingofings** [nosoop/SM-TFCustomAttributeStarterPack#36]
**Initial troubleshooting checklist**
- The Attribute is loaded and is the newest published version compiled with sourcemod 1.10

**Describe the bug**
Permanently breaks the Sentry owners (Engineer only) HUD - Cannot see sentry health, HUD works fine on any other building. Does not need to be affected by a sapper that reprograms. Everyone else (including enemy spies) can see the sentries health

**To Reproduce**
If the attribute is loaded it is enough to not show the Sentry health to the engineer who owns the building

**Expected behavior**
See health like normal

**Server environment (please complete the following information):**
 - Operating System: Ubuntu 20.04.2 LTS
 - SourceMod version: 1.10.0.6502, jit-x86 (build 1.10.0.6502)
 - MetaMod version: 1.11.0-dev+1144

**Additional context**
Screenshot:
![grafik](https://user-images.githubusercontent.com/47538464/108546764-e0d60180-72e9-11eb-8102-dcc43ec79b99.png)

**Comment by nosoop** [comment]
Thanks for the report.  I can't be bothered to look into the underlying cause of this one, but it looks like the owner entity also needs to be recorded separately from the builder.  Will push out a hotfix for that in the next few minutes.
