### ISSUE TITLE
Attributes not reflecting on weapons

### ISSUE THREAD

**Issue by robertsmatt97** [nosoop/SM-TFCustomAttributeStarterPack#38]
**Initial troubleshooting checklist**
- [x] The attribute is loaded, or this bug report is about a plugin load failure.  (Check `sm plugins list` on the server.)
- [x] The attribute is the most recent revision.

**Describe the bug**

After using `tf2attrcustman_reload` and `sm_custattr_show`, It successfully loads the configuration and the custom attributes displayed on my weapon. However, the custom attributes are not actually applied, and the weapon acts as default. I have tried my own attributes, the sample attributes, and native attributes. None of which have worked.

**To Reproduce**

- Downloaded latest versions of each dependency and the Start Pack as of 3/9/2021, with no other plugins installed. Sourcemod and Metamod are installed
- Launched server
- Joined server
- From console, `tf2attrcustman_reload`
- Swapped classes, and then back to original class
- From client, `sm_custattr_show`
- Observed results
- Used `sm_custattr_add [attribute] [value]` to add a near universal native attribute like "fire rate bonus" "0.5"
- `sm_custattr_show` shows newly added attribute, but is not reflected either

**Expected behavior**

Native attributes are not even applied to any weapon. Even simple ones like "max health penalty" on any item will not reflect in game.

**Server environment (please complete the following information):**
 - Operating System: Windows
 - SourceMod version: 1.10.0.6502

**Additional context**

N/A

**Comment by robertsmatt97** [comment]
After using the attributes [listed here](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/wiki/Custom-Attribute-List) as you linked earlier, it worked! Many thanks for your help.

Are there any existing plugins you would recommend that apply native attributes on weapons that do not normally support the functionality, such as Phlog having crits from behind, or stock minigun slowing targets on hit? I attempted to use [tf2x10](https://github.com/50DKP/TF2x10) and load in my own configuration, but very few of the attributes applied (only max health bonuses and bonuses that already existed on the item).

**Comment by nosoop** [comment]
Glad the issue's resolved!  Will go ahead and close the issue.

I don't have any specific endorsements in the applying-native-attributes-with-configuration-files space at this time, unfortunately, though I know [tf2items_manager](https://github.com/asherkin/TF2Items/blob/master/pawn/tf2items_manager.sp) and [Rebalanced Fortress 2](https://github.com/JugadorXEI/tf2rebalance_jug) exist.

My [Attribute Support plugin](https://github.com/nosoop/SM-TFAttributeSupport) is intended to patch over attribute combinations that the game doesn't support.  I think your first two examples are supported without plugins, but the third would definitely be within scope for that project.
