### ISSUE TITLE
TF_HudNotifyCustom not showing up notification when HUD minmode enabled

### ISSUE THREAD

**Issue by chosenbill** [nosoop/SM-TFCustomAttributeStarterPack#45]
I am aware this is probably not the place where I should have issued this but stocksoup respiratory does not have a section for `issues` and the attribute `attr_sapper_recharge_time` which belongs to here uses TF_HudNotifyCustom, I noticed that that its notifications do not show up when the client does not have cl_hud_minmode convar value as 0, which I believe cannot be changed because `basically` that is how the game was supposed to do when it is on. So I figured I would query the client's convar to decide what to do.

```
public Action OnClientWeaponCanSwitchTo(int client, int weapon) {
	if (weapon != GetPlayerWeaponSlot(client, view_as<int>(1))
			|| g_flClientSapLockTime[client] < GetGameTime()) {
		return Plugin_Continue;
	}
	
	EmitGameSoundToClient(client, "Player.DenyWeaponSelection");
	
	QueryClientConVar(client, "cl_hud_minmode", ConVar_minmode);
	
	// Alternatively we can just allow the weapon switch but also prevent attack 
	SetEntPropFloat(weapon, Prop_Data, "m_flNextPrimaryAttack", g_flClientSapLockTime[client]);
	return Plugin_Handled;
}

// Queries whether the client has cl_hud_minmode enabled or not
public void ConVar_minmode(QueryCookie cookie, int client, ConVarQueryResult result,char [] cvarName,char [] cvarValue){
	if(result == ConVarQuery_Okay)
	{
		PrintToServer("Got into it");
		if(StrEqual(cvarValue,"0",false))
		{
			TF_HudNotifyCustom(client, "obj_status_sapper", TF2_GetClientTeam(client),
			"Sapper is disabled for another %d seconds.",
			RoundToCeil(g_flClientSapLockTime[client] - GetGameTime()));
		}else{
			PrintToChat(client,"Sapper is disabled for another %d seconds.", RoundToCeil(g_flClientSapLockTime[client] - GetGameTime()));
		}
	}else{ 
		PrintToServer("Something went wrong with telling the client about cl_hud_minmode");
	}		
}
```
I do this for my other plugins that use TF_HudNotifyCustom, and reason why not just put the `QueryClientConVar` in the include file is because if it is inside of a quickly repeating function like `think` then the chat can get spammy, which will require one to put a timer, but not in this case.

**Comment by nosoop** [comment]
It'd probably be better to use Custom Status HUD in this particular case, if not hint text or keyhints.

`TF_HudNotifyCustom` was used since it was originally written for a weapon demonstration video.

**Comment by chosenbill** [comment]
Interesting, I didn't know that was a thing I will check it out.

**Comment by nosoop** [comment]
If you'd like, you're welcome to fork the repository, create a branch, patch `attr_sapper_recharge_time` with the status HUD change (likely as a countdown timer like the MvM sapper), and I'd be happy to merge the changes in.

You may also consider using [arthurdead's hudnotifyfix](https://forums.alliedmods.net/showthread.php?t=330969) for this purpose.

**Comment by chosenbill** [comment]
> If you'd like, you're welcome to fork the repository, create a branch, patch `attr_sapper_recharge_time` with the status HUD change (likely as a countdown timer / meter like the MvM sapper), and I'd be happy to merge the changes in.
> 
> You may also consider using [arthurdead's hudnotifyfix](https://forums.alliedmods.net/showthread.php?t=330969) for this purpose.

Nice found, I find using this would be optimal if it worked properly. I tried it on my end and it does not show anything but I still find it fascinating unified solution that I would embrace instead of implementing a check for every future plugin that will use the status HUD. I will try looking into it more.
