### ISSUE TITLE
joke_medigun_mod_drain_health Invalid Handle with DHookEnableDetour

### ISSUE THREAD

**Issue by jack5github** [nosoop/SM-TFCustomAttributeStarterPack#48]
**Initial troubleshooting checklist**
- [X] The attribute is loaded, or this bug report is about a plugin load failure.  (Check `sm plugins list` on the server.)
- [X] The attribute is the most recent revision.

**Describe the bug**
L 07/31/2021 - 12:15:32: [SM] Exception reported: Invalid Handle 0
L 07/31/2021 - 12:15:32: [SM] Blaming: custom-attr-starter-pack\joke_medigun_mod_drain_health.smx
L 07/31/2021 - 12:15:32: [SM] Call stack trace:
L 07/31/2021 - 12:15:32: [SM]   [0] DHookEnableDetour
L 07/31/2021 - 12:15:32: [SM]   [1] Line 69, scripting/joke_medigun_mod_drain_health.sp::OnPluginStart
L 07/31/2021 - 12:15:32: [SM] Unable to load plugin "custom-attr-starter-pack\joke_medigun_mod_drain_health.smx": Error detected in plugin startup (see error logs)

**To Reproduce**
Have the latest versions of DHooks2, Custom Weapons X and all its dependencies installed on a Windows server. This bug might also occur on Linux although my results have been inconclusive across Linux servers.

**Expected behavior**
No plugin errors should take place.

**Server environment (please complete the following information):**
 - Operating System: Microsoft Windows 10 Home 10.0.19042 x64-based PC
 - SourceMod version: 1.10.0.6502, jit-x86

P.S. Could you possibly include a sub-attribute that disables the explosion, gibbing and screaming? I'd prefer for enemies affected by the weapon to simply fall limp.

**Comment by nosoop** [comment]
Latest commit now has the `cattr_medigun_drain_gratuitous_violence` ConVar as a global option to disable the explosion / gibbing / crit death sound effects.

**Comment by jack5github** [comment]
Thanks for the extra ConVar, but this hasn't solved the DHooks issue for me. Do you have any clue as to what would be causing this issue, and why its inconsistent for me across operating systems?

**Comment by nosoop** [comment]
See #31; the error is related to bad signatures when trying to create from the configuration file. You may also need to restart the server, as SourceMod's gamedata caching is a frequent source of headaches.

**Comment by nosoop** [comment]
The DHooks-reported error may be fixed with #50.
