### ISSUE TITLE
generate_rage_on_dmg_patch.smx disable_rage_damage_penalty doesn't disable the damage penalty

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFCustomAttributeStarterPack#56]
I'm using the latest releases and the generate_rage_on_dmg_patch.smx does not load.

I'm using the 0.7.0 sourcescramble extension, the extension is loaded on the linux server.

The damage from the minigun is still reduced reduced.

This is the code I use to set the attribute

TF2CustAttr_SetString(Weapon1, "generate rage on damage patch", "disable_knockback=1.0 disable_rage_damage_penalty=1.0");

The knockback disabling works, I've tried to add the disable rage penalty as it's own by itself, as well as the value to be nothing. 1 and 0

Any ideas why this doesn't apply?

I also use the latest gamedata

**Comment by nosoop** [comment]
Interesting; it looks like the operation at the given location is a multiplication operation, but it's not at all the one expected.  Can't remember where the offset came from.

Should be fixed with some new gamedata; expect a closing commit for this in a minute.
