### ISSUE TITLE
mvm_attributes.sp will not compile

### ISSUE THREAD

**Issue by SoulBlast35** [nosoop/SM-TFCustomAttributeStarterPack#59]
I have all the dependencies installed, including StockSoup and smlib, but the compiler spits back this:
// E:\Servers\mvmserver\tf2\tf\addons\sourcemod\scripting\mvm_attributes.sp(159) : error 017: undefined symbol "SplitStringIter"
// E:\Servers\mvmserver\tf2\tf\addons\sourcemod\scripting\mvm_attributes.sp(159) : error 092: number of arguments does not match definition

**Comment by nosoop** [comment]
You'll need to make sure that all the submodules are updated; the commit also changed the pinned version of stocksoup that the project depends on:

```
git submodule update --remote --checkout
```
