### ISSUE TITLE
generate_rage_on_dmg_patch.smx doesn't load

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFCustomAttributeStarterPack#66]
Linux based server:

Error:
L 07/23/2022 - 15:46:49: [SM] Exception reported: Failed to locate signature for 'CTFGameRules::ApplyOnDamageAliveModifyRules()::HeavyRageDamagePenalty' (mempatch 'CTFGameRules::ApplyOnDamageAliveModifyRules()::DisableHeavyRageDamagePenalty')
L 07/23/2022 - 15:46:49: [SM] Blaming: mmattributes/generate_rage_on_dmg_patch.smx
L 07/23/2022 - 15:46:49: [SM] Call stack trace:
L 07/23/2022 - 15:46:49: [SM]   [0] MemoryPatch.CreateFromConf
L 07/23/2022 - 15:46:49: [SM]   [1] Line 52, scripting/generate_rage_on_dmg_patch.sp::OnPluginStart
L 07/23/2022 - 15:46:49: [SM] Unable to load plugin "mmattributes/generate_rage_on_dmg_patch.smx": Error detected in plugin startup (see error logs)

I have updated with the latest package, compiled it myself, but it still throws this error when loading. Is there some undocumented dependency that's missing?

**Comment by nosoop** [comment]
Are you running 1.10?  It's probably alliedmodders/sourcemod#1495 since that isn't backported, annoyingly.

Should be fixed shortly; thanks for the heads-up.
