### ISSUE TITLE
`sniper rifle zoomed reload` Improper damage after first shot

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFCustomAttributeStarterPack#71]
Build 91d60db

**Bug**
`sniper rifle zoomed reload`
All shots after the first (initial scoped) shot, do not benefit from charge effects, and do base damage values.

https://user-images.githubusercontent.com/35093438/188021949-bf40ecb2-4666-46a2-b111-0f5f87d8730c.mp4

NOTE:
Yes, I'm using a hitman's, its "Focus" effects are removed- Its stock in all but name

```
            "mod soldier buff type"		"0"
            //Remove Hitman's Focus effect
```

**To Reproduce**
Set: 
```
            "sniper rifle zoomed reload"		"1"
            //Reloads while zoomed
```
scope, fire a shot, then fully charge the second shot- it will do 'quick scope' damage, not charged damage

**Expected behavior**
Charge should still effect follow-up shots, as it effects the first (and standard) shot(s).

**Server environment (please complete the following information):**
Server OS: Linux, name specific version if possible]
SourceMod Version: 1.10.0.6528

**Additional context**
Attributes In code:
```
    "The Hitman's Heatmaker"
    {

        "attributes"
        {
            "mod soldier buff type"		"0"
            //Remove Hitman's Focus effect
        }
        "custom_attributes"
        {
            "sniper rifle zoomed reload"		"1"
            //Reloads while zoomed
        }
    }    
```

**Comment by nosoop** [comment]
Good catch.  I think this attribute might need a bit of a rework since it does process its check fairly often, but that's for another time.
