### ISSUE TITLE
Soft crash

### ISSUE THREAD

**Issue by JonJonsonsSon** [nosoop/SM-TFCustomAttributeStarterPack#73]
Sometimes, when one map changes to another on my server, clients get stuck at "Downloading sound/weapons/talos/talos_boost_loop.wav." In the console, the message that appears whenever this happens is "CreateFragmentsFromFile: 'sound/weapons/talos/talos_boost_loop.wav' doesn't exist." This happens roughly 40% of the time that the map changes from one to another. Clients can cancel attempting to download the file & reconnect to the server when this happens
Included are several logs from around the times when this has happened
[logs.zip](https://github.com/nosoop/SM-TFCustomAttributeStarterPack/files/9632058/logs.zip)

**Comment by nosoop** [comment]
Fairly sure it's not a soft crash; it just takes a while to time out the download.
Thanks for the report though; I might as well drop the custom logic from the builds.
