### ISSUE TITLE
generate rage on damage patch causes segmentation fault after TF2 update

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFCustomAttributeStarterPack#74]
The generate rage on damage patch.smx causes a segmentation fault.

https://crash.limetech.org/goadsa6yqp5n

Appears to be related to the mempatch

**Comment by nosoop** [comment]
It's tempting to remove the plugin entirely at this point.  Too much of a maintenance burden.

**Comment by nosoop** [comment]
That said, the segfault is more of a Source Scramble issue &mdash; nosoop/SMExt-SourceScramble#12 is intended to fix it, but I haven't gotten around to actually testing nor building a release for it.
