### ISSUE TITLE
`minigun_vacuum.sp` requests sound file not included with files.

### ISSUE THREAD

**Issue by sniggyfigbat** [nosoop/SM-TFCustomAttributeStarterPack#75]
Line 21 of `minigun_vacuum.sp`:

```
#define SOUND_VACUUM_KILL "weapons/enemy_sweeper/vacuum_suck.wav"
```

As this file isn't included and it isn't specified as something to take note of in the installation instructions, I don't have the file set up in my fastdl server, and it seems like this may break fastdl (see the note in the second section [here](https://developer.valvesoftware.com/wiki/FastDL)).

**Comment by nosoop** [comment]
Thanks for the heads-up; should be fixed in the next release.
