### ISSUE TITLE
After latest update, CGlobalEntityList::FindEntityInSphere() has incorrect signature

### ISSUE THREAD

**Issue by higps** [nosoop/SM-TFCustomAttributeStarterPack#77]
The signature

			"CGlobalEntityList::FindEntityInSphere"
			{
				"library"   "server"
				"windows"   "\x55\x8B\xEC\x83\xEC\x0C\x53\x56\x57\x8B\xF9\x8B\x4D\x2A"
				"linux"     "@_ZN17CGlobalEntityList18FindEntityInSphereEP11CBaseEntityRK6Vectorf"
			}
			
Is no longer correct and causes crashes or plugin to simply not load.

**Comment by higps** [comment]
This appears to be linux only, as windows seems to work

**Comment by naydef** [comment]
Seems to affect Windows, too.

Crash: https://crash.limetech.org/3si5xkxbxxte

**Comment by nosoop** [comment]
Windows signature is unchanged, though plugins will need to fix their `SDKCall`s to pass `NULL` in as the last parameter.
