### ISSUE TITLE
`mod crit type on hitgroup` unresponsive

### ISSUE THREAD

**Issue by PonyPhreak** [nosoop/SM-TFCustomAttributeStarterPack#78]
Build a1c66e3

`mod crit type on hitgroup` appears unresponsive. It functioned previously, but recently stopped detecting 'headshots' entirely.

In code: (Used on a custom SMG)
```
        "custom_attributes"
        {
        	"mod crit type on hitgroup"	"hitgroup=1 crit_type=1"
        	//Minicrits on headshot
        }
```
Note: Did attempt: 'Hitgroup=HITGROUP_HEAD` w/ same results

**Server environment:**
 - Operating System: Linux, Debian
 - SourceMod version: SourceMod 1.12.0.6948

**Comment by nosoop** [comment]
Might've been a design mistake &mdash; try [this build of the OnTakeDamage dependency](https://github.com/nosoop/SM-TFOnTakeDamage/releases/tag/r1-entindex).

**Comment by PonyPhreak** [comment]
Yep, that fixed it!
