### ISSUE TITLE
Not sure what I'm doing wrong

### ISSUE THREAD

**Issue by JonJonsonsSon** [nosoop/SM-TFCustomAttributeStarterPack#80]
- [X] The attribute is loaded, or this bug report is about a plugin load failure.  (Check `sm plugins list` on the server.)
- [X] The attribute is the most recent revision.

EDIT: PEBKAC, and I'm unable to delete this thread. Solution that ended up working for me, should anyone else have similar difficulties:

```
"0014"
{
	"name"			"Pootis"
	"inherits"		"The Sandvich"
    	"used_by_classes"	{"heavy" "secondary"}
    	"keep_static_attrs"	"0"
	"attributes_custom" {
        	"custom lunchbox effect" "sugar frenzy"
		"sugar frenzy drink properties" "duration=8 mult_reload_time=6 mult_movespeed=6"
   	 }
}
```

This is how you use custom attributes. I've been using CWX for a long time without custom attributes and I finally figured out the syntax to get them to work just now.

**Comment by nosoop** [comment]
Still a useful issue to raise, since that means the documentation wasn't clear.  Thanks; I've added examples to the custom buff / lunchbox effect pages.

(Aside: `attributes_custom` is the correct section name for CWX; other plugins may integrate the custom attribute framework using other names.)
