### ISSUE TITLE
Gamedata update required for 8216530

### ISSUE THREAD

**Issue by nosoop** [nosoop/SM-TFCustomAttributeStarterPack#83]
Placeholder issue so nobody thinks it's not known.

**Comment by M60TM** [comment]
"CTFPlayerShared::PulseRageBuff()"'s window signatures is changed.
new - `\x55\x8B\xEC\x83\xEC\x18\x33\xC0\xC7\x45\xF8\x83\x00\x00\x00`

**Comment by M60TM** [comment]
"CTFPlayer::GetObjectOfType()"
new - `\x55\x8B\xEC\x51\x53\x8B\xC1\x56\x57\x33\xFF\x89\x45\xFC\x8B\x98\x44\x23\x00\x00`

"CBaseObject::DestroyScreens()"
new - `"\x56\x57\x8B\xF9\x8B\xB7\xEC\x09\x00\x00"`

**Comment by nosoop** [comment]
I've made my own signatures with wildcards for the low bits (`CBaseObject::DestroyScreens()` should be fine since that was already masked), but thank you for the contributions.
