### ISSUE TITLE
First time setup, errors when creating detours

### ISSUE THREAD

**Issue by KatToTheFourth** [nosoop/SM-TFCustomAttributeStarterPack#92]
**Initial troubleshooting checklist**
- [x ] The attribute is loaded, or this bug report is about a plugin load failure.  (Check `sm plugins list` on the server.)
- [ x] The attribute is the most recent revision.

**Describe the bug**
many plugins having failed to create detour errors

**To Reproduce**
Attempt to load plugins

**Expected behavior**
plugins should load

**Server environment (please complete the following information):**
 - Operating System: Windows 11
 - SourceMod version: 1.11 latest

L 07/24/2024 - 00:42:34: Info (map "ctf_2fort") (file "c:\users\koolg\downloads\release\servers\testserver\server\tf\addons\sourcemod\logs\errors_20240724.log")
L 07/24/2024 - 00:42:34: [SM] Exception reported: Failed to create detour CTFWeaponBaseMelee::SecondaryAttack()
L 07/24/2024 - 00:42:34: [SM] Blaming: custom-attr-starter-pack\alt_fire_throws_cleaver.smx
L 07/24/2024 - 00:42:34: [SM] Call stack trace:
L 07/24/2024 - 00:42:34: [SM]   [0] SetFailState
L 07/24/2024 - 00:42:34: [SM]   [1] Line 52, scripting/alt_fire_throws_cleaver.sp::OnPluginStart
L 07/24/2024 - 00:42:34: [SM] Unable to load plugin "custom-attr-starter-pack\alt_fire_throws_cleaver.smx": Error detected in plugin startup (see error logs)
L 07/24/2024 - 00:43:14: [custom-attr-starter-pack\flare_mods.smx] Address for CTFProjectile_Flare::Explode_Air()::SelfDamageRadius contains unexpected value 74000010 (40564896578555790000000000000000.000000)
L 07/24/2024 - 00:43:28: [SM] Exception reported: Failed to create detour CTFLunchBox::SecondaryAttack()
L 07/24/2024 - 00:43:28: [SM] Blaming: custom-attr-starter-pack\lunchbox_override_pickup_type.smx
L 07/24/2024 - 00:43:28: [SM] Call stack trace:
L 07/24/2024 - 00:43:28: [SM]   [0] SetFailState
L 07/24/2024 - 00:43:28: [SM]   [1] Line 29, scripting/lunchbox_override_pickup_type.sp::OnPluginStart
L 07/24/2024 - 00:43:28: [SM] Unable to load plugin "custom-attr-starter-pack\lunchbox_override_pickup_type.smx": Error detected in plugin startup (see error logs)
L 07/24/2024 - 00:44:13: [SM] Exception reported: Failed to create detour CTFMechanicalArm::ShockAttack()
L 07/24/2024 - 00:44:13: [SM] Blaming: custom-attr-starter-pack\weapon_overheat.smx
L 07/24/2024 - 00:44:13: [SM] Call stack trace:
L 07/24/2024 - 00:44:13: [SM]   [0] SetFailState
L 07/24/2024 - 00:44:13: [SM]   [1] Line 94, scripting/weapon_overheat.sp::OnPluginStart
L 07/24/2024 - 00:44:13: [SM] Unable to load plugin "custom-attr-starter-pack\weapon_overheat.smx": Error detected in plugin startup (see error logs)
L 07/24/2024 - 00:44:16: [SM] Exception reported: Hook not setup for a detour.
L 07/24/2024 - 00:44:16: [SM] Blaming: tf_ontakedamage.smx
L 07/24/2024 - 00:44:16: [SM] Call stack trace:
L 07/24/2024 - 00:44:16: [SM]   [0] DynamicDetour.Enable
L 07/24/2024 - 00:44:16: [SM]   [1] Line 51, scripting/tf_ontakedamage.sp::OnPluginStart
L 07/24/2024 - 00:44:16: [SM] Unable to load plugin "tf_ontakedamage.smx": Error detected in plugin startup (see error logs)
L 07/24/2024 - 01:08:47: SourceMod error session started
L 07/24/2024 - 01:08:47: Info (map "ctf_2fort") (file "c:\users\koolg\downloads\release\servers\testserver\server\tf\addons\sourcemod\logs\errors_20240724.log")
L 07/24/2024 - 01:08:47: [SM] Exception reported: Failed to create detour CTFWeaponBaseMelee::SecondaryAttack()
L 07/24/2024 - 01:08:47: [SM] Blaming: custom-attr-starter-pack\alt_fire_throws_cleaver.smx
L 07/24/2024 - 01:08:47: [SM] Call stack trace:
L 07/24/2024 - 01:08:47: [SM]   [0] SetFailState
L 07/24/2024 - 01:08:47: [SM]   [1] Line 52, scripting/alt_fire_throws_cleaver.sp::OnPluginStart
L 07/24/2024 - 01:08:47: [SM] Unable to load plugin "custom-attr-starter-pack\alt_fire_throws_cleaver.smx": Error detected in plugin startup (see error logs)
L 07/24/2024 - 01:09:27: [custom-attr-starter-pack\flare_mods.smx] Address for CTFProjectile_Flare::Explode_Air()::SelfDamageRadius contains unexpected value 74000010 (40564896578555790000000000000000.000000)
L 07/24/2024 - 01:09:45: [SM] Exception reported: Failed to create detour CTFLunchBox::SecondaryAttack()
L 07/24/2024 - 01:09:45: [SM] Blaming: custom-attr-starter-pack\lunchbox_override_pickup_type.smx
L 07/24/2024 - 01:09:45: [SM] Call stack trace:
L 07/24/2024 - 01:09:45: [SM]   [0] SetFailState
L 07/24/2024 - 01:09:45: [SM]   [1] Line 29, scripting/lunchbox_override_pickup_type.sp::OnPluginStart
L 07/24/2024 - 01:09:45: [SM] Unable to load plugin "custom-attr-starter-pack\lunchbox_override_pickup_type.smx": Error detected in plugin startup (see error logs)

**Comment by nosoop** [comment]
Hi; this is being tracked at #90.
You can delete the plugins of any attributes that you don't intend to use to avoid error messages from those, otherwise you'll want to watch that issue for updates.
